### PR TITLE
Fix skew in hash computation

### LINKED ISSUE #18: Hash impl is pretty poor
The current implementation of `Hash` is pretty poor, and leads to lots of collisions for both fractional and whole numbers. For example, the following snippet yields only ~50% unique hash codes.

```
        let state = RandomState::new();
        let limit = 10000;

        let mut set = ::std::collections::HashSet::with_capacity(limit);
        for i in 0..limit {
            let mut h = state.build_hasher();
            OrderedFloat::from(i as f64).hash(&mut h);
            set.insert(h.finish());
        }
        let pct_unique = set.len() as f64 / limit as f64;
        println!("percent-unique={}", pct_unique);
```

A better implementation would be to interpret the `Float` bits as a `u64` and hash that value directly, taking into account `NaN` and `Zero` equivalencies. The JDK's `Double.hashCode()` is a [good example](http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/687fd7c7986d/src/share/classes/java/lang/Double.java) of this.

### PR DESCRIPTION
**Pull request by mhseiden**
This fixes #18 by introducing a better implementation of `Hash` which improves the added tests such that neither has any collisions. Previously, the whole number test had `~50%` unique hash codes, and the fractional test had `~80%` unique hash codes.

Also, my  `auto-rustfmt` kicked in on a few lines, hence the unrelated whitespace changes.

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -66,11 +77,7 @@ impl<T: Float + PartialOrd> Ord for OrderedFloat<T> {
 impl<T: Float + PartialEq> PartialEq for OrderedFloat<T> {
     fn eq(&self, other: &OrderedFloat<T>) -> bool {
         if self.as_ref().is_nan() {
-            if other.as_ref().is_nan() {
-                true
-            } else {
-                false
-            }
+            if other.as_ref().is_nan() { true } else { false }
```
Comment (reem) [inline src/lib.rs]: it occurs to me that this should just be `other.as_ref().is_nan()` the `if/else` is totally unnecessary

note: I know this is just an automated whitespace change but if it's convenient feel free to make the change

File: src/lib.rs [hunk 2]
```diff
@@ -496,7 +503,7 @@ pub struct FloatIsNaN;
 
 impl Error for FloatIsNaN {
     fn description(&self) -> &str {
-        return "NotNaN constructed with NaN"
+        return "NotNaN constructed with NaN";
```
Comment (reem) [inline src/lib.rs]: this could also just be the literal

**Comment by reem** [comment]
I noticed some random stuff that could be improved, but since it's unrelated to your excellent change I'll just go ahead and merge this.
